name: SomnusManager
main: com.yahoo.prosfis.somnusmanager.SomnusManager
version: 1.0.0

commands:
     arena:
        description: All arena commands
        usage: /<command> help
        permission: SomnusManager.arena
        permission-message: You do not have <permission>
permissions:
    SomnusManager.*:
        description: Gives access to all RPGClasses commands.
        children:
            SomnusManager.arena: true
    SomnusManager.arena:
        description: All arena commands
        default: true
